---
ratings:
  paths:
  - "src/**/*"
  - "**.js"
engines:
 csslint:
   enabled: true
   checks:
      box-sizing:
        enabled: false
 eslint:
   enabled: true
 fixme:
   enabled: false

exclude_paths:
- src/public/css/flexboxgrid.min.css
- src/public/css/fonts/roboto/style.css
- src/public/css/font-icons/material-icons/style.css
- src/public/css/font-icons/material-ui-icons/style.css
